#!/bin/bash

### BEGIN INIT INFO
# Provides:          net-monitor-mobile
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: manage the net-monitor-mobile script.
### END INIT INFO
NAME=net-monitor-mobile
SCRIPT=/opt/net-monitor/$NAME.sh
PIDFILE=/var/run/${NAME}.pid

. /lib/lsb/init-functions

start () {
	if [ -f $PIDFILE ]; then
	   log_failure_msg ?Process running already?
	   exit 1
        fi
	start-stop-daemon --start -b --pidfile \
           $PIDFILE --make-pidfile \
             --exec $SCRIPT
	log_success_msg ?$NAME started?
}

stop () {
	if [ -f $PIDFILE ]; then
	   PID=`cat $PIDFILE`
	   #check that the process is running
	   if `ps $PID >/dev/null` ; then
		kill -TERM $PID
		log_success_msg ?Process stopped?
	   else
		log_failure_msg ?Process not running?
	   fi
           # remove pidfile anyhow
	   rm $PIDFILE
	else
	   log_failure_msg ?Process not running?
	fi
}
case $1 in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
	        if [ -f $PIDFILE ]; then
		   PID=`cat $PIDFILE`
		   #check that the process is running
		   if `ps $PID >/dev/null` ; then
			log_success_msg ?Process running?
		   else
		        log_warn_msg ?Process has failed... removing pidfile?
			rm $PIDFILE
		   fi
                 else
			log_success_msg ?Process not running?
		 fi
		 ;;
	restart)
		 stop
		 start
		 ;;
	*)
		echo $?Usage: $0 {start|stop|status}?
		RETVAL=2
esac
